// Generated by scripts/extract-cantonese-adventist-audio-manifest.mjs.
// Contains public media URLs only.

export const CANTONESE_ADVENTIST_AUDIO_URLS: Readonly<Record<string, string>> = Object.freeze({
});
