// Generated by scripts/extract-wordproject-audio-manifest.mjs rv1909.
// Contains public media URLs only.

export const RV1909_ADVENTIST_AUDIO_URLS: Readonly<Record<string, string>> = Object.freeze({
});
