const { withAppBuildGradle } = require('@expo/config-plugins');

const MARKER = 'NYCCSDA_ANDROID_LOCAL_SIGNING';

/**
 * Configure the generated Android release variant to use credentials supplied
 * by the build environment. The keystore and passwords never belong in the
 * Expo config or generated native project.
 */
function withAndroidLocalSigning(config) {
  return withAppBuildGradle(config, (modConfig) => {
    if (modConfig.modResults.language !== 'groovy') {
      throw new Error(
        'withAndroidLocalSigning only supports the generated Groovy Gradle file',
      );
    }

    let contents = modConfig.modResults.contents;
    if (contents.includes(MARKER)) {
      return modConfig;
    }

    const signingConfigsMarker = '    signingConfigs {\n';
    if (!contents.includes(signingConfigsMarker)) {
      throw new Error(
        'Could not find the Android signingConfigs block generated by Expo',
      );
    }

    const signingConfig = `    // ${MARKER}: values are provided through CI/local environment variables.\n`;
    const releaseConfig = `        release {
            def signingKeystorePath = System.getenv('ANDROID_KEYSTORE_PATH')
            def signingKeystorePassword = System.getenv('ANDROID_KEYSTORE_PASSWORD')
            def signingKeyAlias = System.getenv('ANDROID_KEY_ALIAS')
            def signingKeyPassword = System.getenv('ANDROID_KEY_PASSWORD')
            if (signingKeystorePath && signingKeystorePassword && signingKeyAlias && signingKeyPassword) {
                storeFile file(signingKeystorePath)
                storePassword signingKeystorePassword
                keyAlias signingKeyAlias
                keyPassword signingKeyPassword
            }
        }
`;
    contents = contents.replace(
      signingConfigsMarker,
      `${signingConfigsMarker}${signingConfig}${releaseConfig}`,
    );

    const buildTypesStart = contents.indexOf('    buildTypes {');
    const releaseBlockStart = contents.indexOf('        release {', buildTypesStart);
    const releaseSigningText = 'signingConfig signingConfigs.debug';
    const releaseSigningLine = contents.indexOf(releaseSigningText, releaseBlockStart);
    if (
      buildTypesStart === -1 ||
      releaseBlockStart === -1 ||
      releaseSigningLine === -1
    ) {
      throw new Error(
        'Could not find the generated Android release signing configuration',
      );
    }

    contents =
      contents.slice(0, releaseSigningLine) +
      `if (System.getenv('ANDROID_DEBUG_SIGNING_BUILD') == 'true') {
            signingConfig signingConfigs.debug
        } else {
            signingConfig signingConfigs.release
        }` +
      contents.slice(releaseSigningLine + releaseSigningText.length);

    const dependenciesMarker = '\ndependencies {';
    if (!contents.includes(dependenciesMarker)) {
      throw new Error('Could not find the generated Android dependencies block');
    }

    const validation = `
// ${MARKER}: fail signed release builds before Gradle tries to use an empty config.
tasks.configureEach { task ->
    if (task.name == 'bundleRelease' || task.name == 'assembleRelease') {
        doFirst {
            if (System.getenv('ANDROID_DEBUG_SIGNING_BUILD') != 'true') {
                def signingValues = [
                    'ANDROID_KEYSTORE_PATH': System.getenv('ANDROID_KEYSTORE_PATH'),
                    'ANDROID_KEYSTORE_PASSWORD': System.getenv('ANDROID_KEYSTORE_PASSWORD'),
                    'ANDROID_KEY_ALIAS': System.getenv('ANDROID_KEY_ALIAS'),
                    'ANDROID_KEY_PASSWORD': System.getenv('ANDROID_KEY_PASSWORD')
                ]
                def missingValues = signingValues.findAll { name, value -> !value }
                if (!missingValues.isEmpty()) {
                    throw new GradleException(
                        "Missing Android release signing environment variables: \${missingValues.keySet().join(', ')}"
                    )
                }
                if (!file(System.getenv('ANDROID_KEYSTORE_PATH')).isFile()) {
                    throw new GradleException(
                        "Android keystore does not exist at \${System.getenv('ANDROID_KEYSTORE_PATH')}"
                    )
                }
            }
        }
    }
}
`;
    contents = contents.replace(dependenciesMarker, `${validation}${dependenciesMarker}`);

    modConfig.modResults.contents = contents;
    return modConfig;
  });
}

module.exports = withAndroidLocalSigning;
