const {
  AndroidConfig,
  withAndroidManifest,
  withMainActivity,
} = require('@expo/config-plugins');

const MARKER = 'NYCCSDA_PHONE_PORTRAIT';

const CLASS_START = 'class MainActivity : ReactActivity() {\n';
const SUPER_ON_CREATE = '    super.onCreate(';
const IMPORTS = [
  'import android.content.pm.ActivityInfo',
  'import android.content.res.Configuration',
  'import android.os.Build',
];

const MEMBERS = `  // ${MARKER}: phones stay in portrait. Tablets and unfolded foldables
  // (smallest width 600dp or more) turn freely, which Android 16 requires.
  override fun onConfigurationChanged(newConfig: Configuration) {
    super.onConfigurationChanged(newConfig)
    lockPortraitOnPhones()
  }

  private fun lockPortraitOnPhones() {
    val smallestWidthDp = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
      val bounds = windowManager.maximumWindowMetrics.bounds
      minOf(bounds.width(), bounds.height()) / resources.displayMetrics.density
    } else {
      resources.configuration.smallestScreenWidthDp.toFloat()
    }
    requestedOrientation = if (smallestWidthDp < 600) {
      ActivityInfo.SCREEN_ORIENTATION_PORTRAIT
    } else {
      ActivityInfo.SCREEN_ORIENTATION_UNSPECIFIED
    }
  }

`;

/** Removes the manifest's orientation lock, which Play flags for large screens. */
function removeManifestOrientation(manifest) {
  const mainActivity = AndroidConfig.Manifest.getMainActivityOrThrow(manifest);
  delete mainActivity.$['android:screenOrientation'];
  return manifest;
}

/** Locks portrait at run time instead, on phones only. */
function addPhonePortraitLock(contents) {
  if (contents.includes(MARKER)) {
    return contents;
  }
  if (!contents.includes(CLASS_START) || !contents.includes(SUPER_ON_CREATE)) {
    throw new Error('Could not find the MainActivity class and onCreate generated by Expo');
  }

  const missingImports = IMPORTS.filter((line) => !contents.includes(`${line}\n`));
  contents = contents.replace(/^package .+\n/, (line) => `${line}\n${missingImports.join('\n')}\n`);
  // Ask before the first layout, so a phone held sideways at launch doesn't
  // lay the app out in landscape first.
  contents = contents.replace(SUPER_ON_CREATE, `    lockPortraitOnPhones()\n${SUPER_ON_CREATE}`);
  return contents.replace(CLASS_START, `${CLASS_START}${MEMBERS}`);
}

/**
 * Android 16 ignores orientation locks on large screens, and Play flags apps
 * that set one (#426). Phones keep the portrait-only layout the app is designed
 * for. iOS isn't touched: app.json's "orientation" still sets the iPhone to
 * portrait.
 */
function withAndroidPhonePortrait(config) {
  config = withAndroidManifest(config, (modConfig) => {
    modConfig.modResults = removeManifestOrientation(modConfig.modResults);
    return modConfig;
  });
  return withMainActivity(config, (modConfig) => {
    if (modConfig.modResults.language !== 'kt') {
      throw new Error('withAndroidPhonePortrait only supports the generated Kotlin MainActivity');
    }
    modConfig.modResults.contents = addPhonePortraitLock(modConfig.modResults.contents);
    return modConfig;
  });
}

module.exports = withAndroidPhonePortrait;
module.exports.addPhonePortraitLock = addPhonePortraitLock;
module.exports.removeManifestOrientation = removeManifestOrientation;
